.TH "aboutdialog.h" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
aboutdialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBAboutDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsqlitetest\fP"
.br
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
