.TH "AboutDialog" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
AboutDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <aboutdialog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBAboutDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~AboutDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 46 of file aboutdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBAboutDialog::AboutDialog\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 40 of file aboutdialog\&.cpp\&.
.SS "\fBAboutDialog::~AboutDialog\fP ()"
.PP
Definition at line 47 of file aboutdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
