.TH "helpsetdialog.cpp" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helpsetdialog.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include 'helpsetdialog\&.h'\fP
.br
\fC#include 'ui_helpsetdialog\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsqlitetest\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
