.TH "HelpSetDialog" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
HelpSetDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <helpsetdialog\&.h>\fP
.SS "Public Slots"

.in +1c
.ti -1c
.RI "void \fBClickedHome\fP ()"
.br
.ti -1c
.RI "void \fBClickedGit\fP ()"
.br
.ti -1c
.RI "void \fBClickedClose\fP ()"
.br
.ti -1c
.RI "void \fBClickedBack\fP ()"
.br
.ti -1c
.RI "void \fBClickedForward\fP ()"
.br
.ti -1c
.RI "void \fBClickedRefresh\fP ()"
.br
.ti -1c
.RI "void \fBClickedH0\fP ()"
.br
.ti -1c
.RI "void \fBClickedH1\fP ()"
.br
.ti -1c
.RI "void \fBClickedH2\fP ()"
.br
.ti -1c
.RI "void \fBClickedH3\fP ()"
.br
.ti -1c
.RI "void \fBClickedH4\fP ()"
.br
.ti -1c
.RI "void \fBClickedH5\fP ()"
.br
.ti -1c
.RI "void \fBClickedH6\fP ()"
.br
.ti -1c
.RI "void \fBClickedH7\fP ()"
.br
.ti -1c
.RI "void \fBClickedH8\fP ()"
.br
.in -1c
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBHelpSetDialog\fP (bool firstCall, QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~HelpSetDialog\fP ()"
.br
.ti -1c
.RI "void \fBcloseEvent\fP (QCloseEvent *event)"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 50 of file helpsetdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBHelpSetDialog::HelpSetDialog\fP (boolfirstCall, QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 40 of file helpsetdialog\&.cpp\&.
.SS "\fBHelpSetDialog::~HelpSetDialog\fP ()"
.PP
Definition at line 52 of file helpsetdialog\&.cpp\&.
.SH "Member Function Documentation"
.PP 
.SS "void \fBHelpSetDialog::ClickedBack\fP ()\fC [slot]\fP"
.PP
Definition at line 123 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedClose\fP ()\fC [slot]\fP"
.PP
Definition at line 116 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedForward\fP ()\fC [slot]\fP"
.PP
Definition at line 126 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedGit\fP ()\fC [slot]\fP"
.PP
Definition at line 143 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH0\fP ()\fC [slot]\fP"
.PP
Definition at line 150 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH1\fP ()\fC [slot]\fP"
.PP
Definition at line 156 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH2\fP ()\fC [slot]\fP"
.PP
Definition at line 162 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH3\fP ()\fC [slot]\fP"
.PP
Definition at line 168 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH4\fP ()\fC [slot]\fP"
.PP
Definition at line 175 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH5\fP ()\fC [slot]\fP"
.PP
Definition at line 181 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH6\fP ()\fC [slot]\fP"
.PP
Definition at line 187 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH7\fP ()\fC [slot]\fP"
.PP
Definition at line 194 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedH8\fP ()\fC [slot]\fP"
.PP
Definition at line 202 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedHome\fP ()\fC [slot]\fP"
.PP
Definition at line 133 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::ClickedRefresh\fP ()\fC [slot]\fP"
.PP
Definition at line 120 of file helpsetdialog\&.cpp\&.
.SS "void \fBHelpSetDialog::closeEvent\fP (QCloseEvent *event)"
.PP
Definition at line 92 of file helpsetdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
