.TH "helpsetdialog.h" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
helpsetdialog.h \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QDialog>\fP
.br
\fC#include <QMessageBox>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br
\fC#include 'sqlite\&.h'\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBHelpSetDialog\fP"
.br
.in -1c
.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsqlitetest\fP"
.br
.ti -1c
.RI "namespace \fBUi\fP"
.br
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
