.TH "main.cpp" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
main.cpp \- 
.SH SYNOPSIS
.br
.PP
\fC#include <QtGui/QApplication>\fP
.br
\fC#include 'mainwindow\&.h'\fP
.br

.SS "Namespaces"

.in +1c
.ti -1c
.RI "namespace \fBsqlitetest\fP"
.br
.in -1c
.SS "Functions"

.in +1c
.ti -1c
.RI "int \fBmain\fP (int argc, char *argv[])"
.br
.in -1c
.SH "Function Documentation"
.PP 
.SS "int \fBmain\fP (intargc, char *argv[])"
.PP
Definition at line 40 of file main\&.cpp\&.
.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
