.TH "ResultDialog" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
ResultDialog \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <resultdialog\&.h>\fP
.SS "Public Member Functions"

.in +1c
.ti -1c
.RI "\fBResultDialog\fP (QWidget *parent=0)"
.br
.ti -1c
.RI "\fB~ResultDialog\fP ()"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 49 of file resultdialog\&.h\&.
.SH "Constructor & Destructor Documentation"
.PP 
.SS "\fBResultDialog::ResultDialog\fP (QWidget *parent = \fC0\fP)\fC [explicit]\fP"
.PP
Definition at line 40 of file resultdialog\&.cpp\&.
.SS "\fBResultDialog::~ResultDialog\fP ()"
.PP
Definition at line 48 of file resultdialog\&.cpp\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
