.TH "SqlPreferences" 3 "Tue Nov 13 2012" "Version 0.3.0a" "SQLiteTest" \" -*- nroff -*-
.ad l
.nh
.SH NAME
SqlPreferences \- 
.SH SYNOPSIS
.br
.PP
.PP
\fC#include <sqlite\&.h>\fP
.SS "Public Attributes"

.in +1c
.ti -1c
.RI "bool \fBuseAtomicCommit\fP"
.br
.ti -1c
.RI "bool \fBuseCustomPageSize\fP"
.br
.ti -1c
.RI "bool \fBuseCustomCacheSize\fP"
.br
.ti -1c
.RI "bool \fBuseCustomTempStore\fP"
.br
.ti -1c
.RI "bool \fBuseCustomJournalMode\fP"
.br
.ti -1c
.RI "bool \fBuseCustomLockingMode\fP"
.br
.ti -1c
.RI "bool \fBuseCustomSynchronous\fP"
.br
.ti -1c
.RI "bool \fBuseExistDB\fP"
.br
.ti -1c
.RI "bool \fBuseRamDB\fP"
.br
.ti -1c
.RI "QString \fBcustomPageSize\fP"
.br
.ti -1c
.RI "QString \fBcustomCacheSize\fP"
.br
.ti -1c
.RI "QString \fBcustomTempStore\fP"
.br
.ti -1c
.RI "QString \fBcustomJournalMode\fP"
.br
.ti -1c
.RI "QString \fBcustomLockingMode\fP"
.br
.ti -1c
.RI "QString \fBcustomSynchronous\fP"
.br
.in -1c
.SH "Detailed Description"
.PP 
Definition at line 54 of file sqlite\&.h\&.
.SH "Member Data Documentation"
.PP 
.SS "QString \fBSqlPreferences::customCacheSize\fP"
.PP
Definition at line 66 of file sqlite\&.h\&.
.SS "QString \fBSqlPreferences::customJournalMode\fP"
.PP
Definition at line 68 of file sqlite\&.h\&.
.SS "QString \fBSqlPreferences::customLockingMode\fP"
.PP
Definition at line 69 of file sqlite\&.h\&.
.SS "QString \fBSqlPreferences::customPageSize\fP"
.PP
Definition at line 65 of file sqlite\&.h\&.
.SS "QString \fBSqlPreferences::customSynchronous\fP"
.PP
Definition at line 70 of file sqlite\&.h\&.
.SS "QString \fBSqlPreferences::customTempStore\fP"
.PP
Definition at line 67 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useAtomicCommit\fP"
.PP
Definition at line 56 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomCacheSize\fP"
.PP
Definition at line 58 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomJournalMode\fP"
.PP
Definition at line 60 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomLockingMode\fP"
.PP
Definition at line 61 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomPageSize\fP"
.PP
Definition at line 57 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomSynchronous\fP"
.PP
Definition at line 62 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useCustomTempStore\fP"
.PP
Definition at line 59 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useExistDB\fP"
.PP
Definition at line 63 of file sqlite\&.h\&.
.SS "bool \fBSqlPreferences::useRamDB\fP"
.PP
Definition at line 64 of file sqlite\&.h\&.

.SH "Author"
.PP 
Generated automatically by Doxygen for SQLiteTest from the source code\&.
